### ISSUE TITLE
Roadmap 1.9

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#161]
Some exciting additions are coming.

New web frameworks for the server: both Node and Go.

For Node, we're adding Koa to the stack, with its version 2.x - which will support `async`/`await`.
For Golang, we're adding Gin, a fast and stable web framework.

For the client side, we're adding the possibility to use either `LESS` or `SASS` in your styles (see https://github.com/ericmdantas/generator-ng-fullstack/issues/25);

We're also adding aurelia ([ref](https://github.com/aurelia/framework)) as an option for the client side.

And we'll also implement an option so the user can choose if he wants to work with tests side by side with the source code or in separated folders.

So, in short, this is what we have to finish to get through 1.9:
- [x] Less/Sass support (#25);
- [x] Node - Koa support (#52);
- [x] Go - Gin support (#160);
- [x] Generic git server (#152);
- [x] Nodemon for dev (#157);
- [x] Add `getById` on the boilerplate app - both in client and server (#179);
- [x] Aurelia in the client (#175);
- [x] Vue in the client (#194);
- [x] Option to have source and tests side by side (#173).
- [x] Use npm hooks to run additional scripts (#181);
- [x] Update echo to stable v3 (#180);
- [x] Uses same namings for boilerplate app and what the sub generators create (#177);
- [x] Clean up, naming conventions, folder names, etc.
- [x] Babel/Babili compilation step (#227)
- [x] Update docs with the changes (#178)
- [x] Implement HTTP/2 server for Node (#249)

Edit:
DB changes were moved to 1.11 (https://github.com/ericmdantas/generator-ng-fullstack/issues/170).

**Comment by ccocker** [comment]
Adding Firebase to list of supported DB's would be nice

**Comment by ericmdantas** [comment]
Good suggestion, @ccocker.

My only concern is the size of 1.9, it might take too long to be released, so I might break it into `1.9` and `1.10`. 

1.9:
- Sass/Less;
- Node - Koa;
- Go - Gin;
- Generic git server;

1.10:
- RethinkDB;
- Firebase;
- PostgreSQL;

I'm still thinking about it, though.

**Comment by ericmdantas** [comment]
Generic git support landed in branch `v1.9` via commit bd888b77ad5d7d70826b0ad93ee73e48000095af, PR #164.

**Comment by ericmdantas** [comment]
Alright, in order to have releases relatively close to each other, I'm removing the DB modifications and assigning it to 1.10.0.

**Comment by Abdizriel** [comment]
@ericmdantas when do you plan to release 1.9? It will take some time to release #173

**Comment by ericmdantas** [comment]
@Abdizriel, if everything goes right, this weekend. If not, next week.

**Comment by ericmdantas** [comment]
@Abdizriel, but we can make room for that feature in 1.9, if you want.

**Comment by Abdizriel** [comment]
@ericmdantas I'll try to do that by tomorrow.

**Comment by ericmdantas** [comment]
Pretty much.

**Comment by bernardbr** [comment]
@ericmdantas, maybe you can add aurelia.io as an option to implement
front-end without angular!

Rob Eisenberg left Angular 2 for it:
http://eisenbergeffect.bluespire.com/leaving-angular/

Em qua, 22 de jun de 2016 às 15:01, Eric M. Dantas <notifications@github.com>
escreveu:

> Pretty much.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ericmdantas/generator-ng-fullstack/issues/161#issuecomment-227827018>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEfLCmRBx1VaMxYhfDIwvIOXqiNQVzn-ks5qOXiOgaJpZM4Iw0fL>
> .
>
-- 
Bernardo A.C. Esbérard

**Comment by ericmdantas** [comment]
@bernardbr, nice suggestion.

 I've wanted to give Aurelia a try for a while now - but never got the time. 

Since I haven't used it yet, I'll play with it a bit first, and then, I might target it to `1.9` if it's not a big change, or later, if it's a huge change.

**Comment by ericmdantas** [comment]
Updates roadmap.

**Comment by ericmdantas** [comment]
Adds Vue to the list.

**Comment by ericmdantas** [comment]
As for features, the two left are: Aurelia and Less/Sass.

The other changes are related to documentation and suchs. We're almost there!

**Comment by ericmdantas** [comment]
Adds flat structure to the todo list.

**Comment by ericmdantas** [comment]
1.9 is 90% done. 

There are some minor bugs going on and I`ll have to take care of the docs before releasing it.

**Comment by ericmdantas** [comment]
Note to self: Vue 2.0 is out - update the client.

**Comment by ericmdantas** [comment]
Added babel/babili compilation step for `ng1`, `aurelia` and `vue` to the list.

**Comment by ericmdantas** [comment]
Final steps: update the docs, do some manual tests and we're good to release `v1.9`.

**Comment by ericmdantas** [comment]
Depending on https://github.com/labstack/echo/issues/838.

**Comment by ericmdantas** [comment]
Added HTTP/2 server to the list.

**Comment by ericmdantas** [comment]
Done.
